version: '3.8'

services:
  chronocast_archiver:
    build: ./
    restart: always
    volumes:
      - ./credentials_full.json:/app/credentials.json
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json